//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.BankStatement = new HashSet<BankStatement>();
        }
    
        public System.Guid BankAccountID { get; set; }
        public System.Guid SubscriptionID { get; set; }
        public System.Guid BankID { get; set; }
        public string Agency { get; set; }
        public string AccountNumber { get; set; }
        public decimal InitialBalance { get; set; }
        public System.Guid RegistrationUserID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.Guid> DesactivationUserID { get; set; }
        public Nullable<System.DateTime> DesactivationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankStatement> BankStatement { get; set; }
    }
}
