//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public System.Guid InstallmentID { get; set; }
        public System.Guid InvoiceID { get; set; }
        public System.Guid StatusInstallmentID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.Guid RegistrationUserID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.Guid> DesactivationUserID { get; set; }
        public Nullable<System.DateTime> DesactivationDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual StatusInstallment StatusInstallment { get; set; }
    }
}
