//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankAccount> BankAccount { get; set; }
        public virtual DbSet<BankStatement> BankStatement { get; set; }
        public virtual DbSet<Installment> Installment { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Partner> Partner { get; set; }
        public virtual DbSet<Reconciliation> Reconciliation { get; set; }
        public virtual DbSet<StatusInstallment> StatusInstallment { get; set; }
        public virtual DbSet<StatusInvoice> StatusInvoice { get; set; }
        public virtual DbSet<StatusReconciliation> StatusReconciliation { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TransactionType> TransactionType { get; set; }
    }
}
