//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusInstallment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatusInstallment()
        {
            this.Installment = new HashSet<Installment>();
        }
    
        public System.Guid StatusInstallmentID { get; set; }
        public string Name { get; set; }
        public System.Guid RegistrationUserID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<short> Ordering { get; set; }
        public Nullable<System.Guid> DesactivationUserID { get; set; }
        public Nullable<System.DateTime> DesactivationDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installment { get; set; }
    }
}
